/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ErrorIndexRouteImport } from './routes/error/index'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AdminWarehousesIndexRouteImport } from './routes/admin/warehouses/index'
import { Route as AdminPostsIndexRouteImport } from './routes/admin/posts/index'
import { Route as AdminLaptopsIndexRouteImport } from './routes/admin/laptops/index'
import { Route as AdminDiscountsIndexRouteImport } from './routes/admin/discounts/index'
import { Route as AdminCategoriesIndexRouteImport } from './routes/admin/categories/index'
import { Route as AuthSsoCallbackRouteImport } from './routes/auth/sso/callback'
import { Route as AdminWarehousesStorageRouteImport } from './routes/admin/warehouses/storage'
import { Route as AdminPostsCreateRouteImport } from './routes/admin/posts/create'
import { Route as AdminLaptopsCreateRouteImport } from './routes/admin/laptops/create'
import { Route as AdminDiscountsCreateRouteImport } from './routes/admin/discounts/create'
import { Route as AdminCategoriesBaseRouteImport } from './routes/admin/categories/base'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorIndexRoute = ErrorIndexRouteImport.update({
  id: '/error/',
  path: '/error/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWarehousesIndexRoute = AdminWarehousesIndexRouteImport.update({
  id: '/warehouses/',
  path: '/warehouses/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsIndexRoute = AdminPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLaptopsIndexRoute = AdminLaptopsIndexRouteImport.update({
  id: '/laptops/',
  path: '/laptops/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiscountsIndexRoute = AdminDiscountsIndexRouteImport.update({
  id: '/discounts/',
  path: '/discounts/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesIndexRoute = AdminCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AdminRoute,
} as any)
const AuthSsoCallbackRoute = AuthSsoCallbackRouteImport.update({
  id: '/auth/sso/callback',
  path: '/auth/sso/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWarehousesStorageRoute = AdminWarehousesStorageRouteImport.update({
  id: '/warehouses/storage',
  path: '/warehouses/storage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsCreateRoute = AdminPostsCreateRouteImport.update({
  id: '/posts/create',
  path: '/posts/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLaptopsCreateRoute = AdminLaptopsCreateRouteImport.update({
  id: '/laptops/create',
  path: '/laptops/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiscountsCreateRoute = AdminDiscountsCreateRouteImport.update({
  id: '/discounts/create',
  path: '/discounts/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesBaseRoute = AdminCategoriesBaseRouteImport.update({
  id: '/categories/base',
  path: '/categories/base',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/error/': typeof ErrorIndexRoute
  '/admin/categories/base': typeof AdminCategoriesBaseRoute
  '/admin/discounts/create': typeof AdminDiscountsCreateRoute
  '/admin/laptops/create': typeof AdminLaptopsCreateRoute
  '/admin/posts/create': typeof AdminPostsCreateRoute
  '/admin/warehouses/storage': typeof AdminWarehousesStorageRoute
  '/auth/sso/callback': typeof AuthSsoCallbackRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/discounts/': typeof AdminDiscountsIndexRoute
  '/admin/laptops/': typeof AdminLaptopsIndexRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/admin/warehouses/': typeof AdminWarehousesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/error': typeof ErrorIndexRoute
  '/admin/categories/base': typeof AdminCategoriesBaseRoute
  '/admin/discounts/create': typeof AdminDiscountsCreateRoute
  '/admin/laptops/create': typeof AdminLaptopsCreateRoute
  '/admin/posts/create': typeof AdminPostsCreateRoute
  '/admin/warehouses/storage': typeof AdminWarehousesStorageRoute
  '/auth/sso/callback': typeof AuthSsoCallbackRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/discounts': typeof AdminDiscountsIndexRoute
  '/admin/laptops': typeof AdminLaptopsIndexRoute
  '/admin/posts': typeof AdminPostsIndexRoute
  '/admin/warehouses': typeof AdminWarehousesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/error/': typeof ErrorIndexRoute
  '/admin/categories/base': typeof AdminCategoriesBaseRoute
  '/admin/discounts/create': typeof AdminDiscountsCreateRoute
  '/admin/laptops/create': typeof AdminLaptopsCreateRoute
  '/admin/posts/create': typeof AdminPostsCreateRoute
  '/admin/warehouses/storage': typeof AdminWarehousesStorageRoute
  '/auth/sso/callback': typeof AuthSsoCallbackRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/discounts/': typeof AdminDiscountsIndexRoute
  '/admin/laptops/': typeof AdminLaptopsIndexRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/admin/warehouses/': typeof AdminWarehousesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth/login'
    | '/auth/sign-up'
    | '/error/'
    | '/admin/categories/base'
    | '/admin/discounts/create'
    | '/admin/laptops/create'
    | '/admin/posts/create'
    | '/admin/warehouses/storage'
    | '/auth/sso/callback'
    | '/admin/categories/'
    | '/admin/discounts/'
    | '/admin/laptops/'
    | '/admin/posts/'
    | '/admin/warehouses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth/login'
    | '/auth/sign-up'
    | '/error'
    | '/admin/categories/base'
    | '/admin/discounts/create'
    | '/admin/laptops/create'
    | '/admin/posts/create'
    | '/admin/warehouses/storage'
    | '/auth/sso/callback'
    | '/admin/categories'
    | '/admin/discounts'
    | '/admin/laptops'
    | '/admin/posts'
    | '/admin/warehouses'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth/login'
    | '/auth/sign-up'
    | '/error/'
    | '/admin/categories/base'
    | '/admin/discounts/create'
    | '/admin/laptops/create'
    | '/admin/posts/create'
    | '/admin/warehouses/storage'
    | '/auth/sso/callback'
    | '/admin/categories/'
    | '/admin/discounts/'
    | '/admin/laptops/'
    | '/admin/posts/'
    | '/admin/warehouses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  ErrorIndexRoute: typeof ErrorIndexRoute
  AuthSsoCallbackRoute: typeof AuthSsoCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error/': {
      id: '/error/'
      path: '/error'
      fullPath: '/error/'
      preLoaderRoute: typeof ErrorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/warehouses/': {
      id: '/admin/warehouses/'
      path: '/warehouses'
      fullPath: '/admin/warehouses/'
      preLoaderRoute: typeof AdminWarehousesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts/': {
      id: '/admin/posts/'
      path: '/posts'
      fullPath: '/admin/posts/'
      preLoaderRoute: typeof AdminPostsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/laptops/': {
      id: '/admin/laptops/'
      path: '/laptops'
      fullPath: '/admin/laptops/'
      preLoaderRoute: typeof AdminLaptopsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/discounts/': {
      id: '/admin/discounts/'
      path: '/discounts'
      fullPath: '/admin/discounts/'
      preLoaderRoute: typeof AdminDiscountsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories/': {
      id: '/admin/categories/'
      path: '/categories'
      fullPath: '/admin/categories/'
      preLoaderRoute: typeof AdminCategoriesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/sso/callback': {
      id: '/auth/sso/callback'
      path: '/auth/sso/callback'
      fullPath: '/auth/sso/callback'
      preLoaderRoute: typeof AuthSsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/warehouses/storage': {
      id: '/admin/warehouses/storage'
      path: '/warehouses/storage'
      fullPath: '/admin/warehouses/storage'
      preLoaderRoute: typeof AdminWarehousesStorageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts/create': {
      id: '/admin/posts/create'
      path: '/posts/create'
      fullPath: '/admin/posts/create'
      preLoaderRoute: typeof AdminPostsCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/laptops/create': {
      id: '/admin/laptops/create'
      path: '/laptops/create'
      fullPath: '/admin/laptops/create'
      preLoaderRoute: typeof AdminLaptopsCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/discounts/create': {
      id: '/admin/discounts/create'
      path: '/discounts/create'
      fullPath: '/admin/discounts/create'
      preLoaderRoute: typeof AdminDiscountsCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories/base': {
      id: '/admin/categories/base'
      path: '/categories/base'
      fullPath: '/admin/categories/base'
      preLoaderRoute: typeof AdminCategoriesBaseRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCategoriesBaseRoute: typeof AdminCategoriesBaseRoute
  AdminDiscountsCreateRoute: typeof AdminDiscountsCreateRoute
  AdminLaptopsCreateRoute: typeof AdminLaptopsCreateRoute
  AdminPostsCreateRoute: typeof AdminPostsCreateRoute
  AdminWarehousesStorageRoute: typeof AdminWarehousesStorageRoute
  AdminCategoriesIndexRoute: typeof AdminCategoriesIndexRoute
  AdminDiscountsIndexRoute: typeof AdminDiscountsIndexRoute
  AdminLaptopsIndexRoute: typeof AdminLaptopsIndexRoute
  AdminPostsIndexRoute: typeof AdminPostsIndexRoute
  AdminWarehousesIndexRoute: typeof AdminWarehousesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesBaseRoute: AdminCategoriesBaseRoute,
  AdminDiscountsCreateRoute: AdminDiscountsCreateRoute,
  AdminLaptopsCreateRoute: AdminLaptopsCreateRoute,
  AdminPostsCreateRoute: AdminPostsCreateRoute,
  AdminWarehousesStorageRoute: AdminWarehousesStorageRoute,
  AdminCategoriesIndexRoute: AdminCategoriesIndexRoute,
  AdminDiscountsIndexRoute: AdminDiscountsIndexRoute,
  AdminLaptopsIndexRoute: AdminLaptopsIndexRoute,
  AdminPostsIndexRoute: AdminPostsIndexRoute,
  AdminWarehousesIndexRoute: AdminWarehousesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  ErrorIndexRoute: ErrorIndexRoute,
  AuthSsoCallbackRoute: AuthSsoCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
